### ISSUE TITLE
Alpha release checklist

### ISSUE THREAD

**Issue by mortonjt** [biocore/mmvec#27]
- [x] Travis setup
- [x] Update README with examples + tutorial
- [x] setup.py corrections
- [x] License
- [x] Changelog
- [x] Pip install
- [x] Conda install
- [x] Basic summary command
- [x] q2 rhapsody plugin
